### ISSUE TITLE
Core runs slow on Low end Hardware.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/mupen64plus-libretro-nx#12] opened 2019-01-23 06:32 UTC
This core needs some optomization to run on low end Intel Atom hardware. I use -mtune=atom. It is still slightly too slow in places to run full speed. (Tested with Super Mario 64)

**Comment by m4xw** [comment] 2019-01-23 09:46
GlideN64 is designed with high end hardware in mind.
If you cant even run SM64 fullspeed, you are not even close, 
Tweak your settings, we can run it fullspeed on 800MHz'ish, if it's GlideN64 that bottlenecks you, you are out of luck.

**Comment by Zombie-Ryushu** [comment] 2019-01-23 11:16
I have an ASUS AT3IONT-I Deluxe Intel Atom 330 NVIDIA ION Mini ITX Motherboard.

**Comment by m4xw** [comment] 2019-01-23 11:18
Try Fb emu off, frame dupe off, noise off, less accurate blending mod on, color+depth buffer off.
Report back.

**Comment by Zombie-Ryushu** [comment] 2019-01-24 06:59
Improved things significantly, can run SM64 almost full speed, with an occasional "Skip" but Ocarina of time still has some Audio distortion and lag loading. No where near as bad as it was.

**Comment by m4xw** [comment] 2019-01-24 09:47
What resolution are you at?

**Comment by Zombie-Ryushu** [comment] 2019-01-24 09:52
320x240 I think.

**Comment by m4xw** [comment] 2019-01-24 10:03
Ouch.  I fear its a GPU bottleneck, not much I can do.
Maybe the GlideN upgrade will improve it, but currently you are better of  with parallel and a older gfx plugin.

**Comment by Zombie-Ryushu** [comment] 2019-01-24 10:09
What plugin should I download and compile?

**Comment by Zombie-Ryushu** [comment] 2019-01-24 10:31
I mean from what RetroArch Repo?

**Comment by m4xw** [comment] 2019-01-24 10:42
https://github.com/libretro/parallel-n64

**Comment by Zombie-Ryushu** [comment] 2019-01-24 12:02
That Core performed horrendously. Do you have any others?

**Comment by m4xw** [comment] 2019-01-24 12:10
Nope.

**Comment by Zombie-Ryushu** [comment] 2019-01-24 12:13
what about libretro-mupen64plus?

**Comment by m4xw** [comment] 2019-01-24 12:15
You literally opened a issue there already, I assume you tried it already.
But this Core has the same GlideN64 version as old mupen and the rest is outdated and slower.
Your hardware seems to perform worse than a raspberry pi lol.

**Comment by Zombie-Ryushu** [comment] 2019-01-24 12:23
Its a motherboard from 2010.

**Comment by IntelMiner** [comment] 2019-01-25 09:01
You're using an Intel Atom from 2008. Even at the time that thing was low-end

You may want to consider upgrading to something a bit newer, either ITX or otherwise depending on your needs

**Closed** 2019-01-27 21:47 UTC
Labels: invalid

**Comment by DoktorSeven** [comment] 2019-02-23 22:58
It's just slow, period.  I have not the best CPU, a quad core AMD 2.4GHz, and it runs unplayably slow at a few frames per second.  Running plain mpuen64plus with the Glide64 plugin on the exact same machine runs perfectly.  Something is wrong with your implementation here, or with RetroArch in general.

**Comment by m4xw** [comment] 2019-02-23 23:05
Glide != GlideN
