### ISSUE TITLE
Yoshis Story per pixel lighting regression?

### ISSUE THREAD

**Issue by BParks21** [libretro/mupen64plus-libretro-nx#96] opened 2019-09-10 08:42 UTC
The blocks on the level select screen are now multi colored with per pixel lighting. Previously looked correct with it enabled. Latest core version.

![Yoshi's Story (USA) (En,Ja)-190910-044148](https://user-images.githubusercontent.com/12180630/64598209-5879d000-d385-11e9-99af-d42333e3dfb6.png)
![Yoshi's Story (USA) (En,Ja)-190910-042820](https://user-images.githubusercontent.com/12180630/64598214-5a439380-d385-11e9-9ef9-ea09dac2e440.png)

**Comment by m4xw** [comment] 2019-09-10 08:57
I guess thats a dupe of #86 too.
If it continues after it, please re-open the issue.

**Closed by m4xw** 2019-09-10 08:57 UTC
