### ISSUE TITLE
Battle for Naboo crashes when using ParaLLel

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#257] opened 2020-09-03 21:41 UTC
First level, after the "Star Wars" intro with the scrolling letters. I get a black screen and then it hangs.

**Comment by m4xw** [comment] 2020-09-04 23:29
Does it work with the parallel core?
If too: https://github.com/Themaister/parallel-rdp/issues

**Comment by m4xw** [comment] 2020-09-04 23:30
or... did u mean rsp, lol

**Comment by Tasosgemah** [comment] 2020-09-05 13:40
Yes, it works with the Parallel core.

Though this core has audio issues. But it does load the game after the Star Wars scrolling letters intro.

**Comment by m4xw** [comment] 2020-09-06 22:49
What happens with angrylion

**Comment by m4xw** [comment] 2020-09-06 22:49
Also show me your core options

**Comment by Tasosgemah** [comment] 2020-09-07 01:42
Cant test more right now, ill be away from my PC for a few days

**Comment by Themaister** [comment] 2020-09-12 10:20
I cannot reproduce. Make sure you're using up-to-date graphics drivers.

**Comment by m4xw** [comment] 2020-09-28 15:50
@Tasosgemah any update?

**Comment by m4xw** [comment] 2020-09-28 19:56
Will close this for now, we can reopen as needed.

**Closed by m4xw** 2020-09-28 19:56 UTC

**Comment by Tasosgemah** [comment] 2020-09-28 23:36
> Will close this for now, we can reopen as needed.

Sorry for the late reply.

I'm still getting the same crash at the same spot. Can reproduce it 100% of the time.

Here's my option file:

https://pastebin.pl/view/576b3ed2

**Comment by Tynach** [comment] 2022-06-26 18:41
@m4xw, @Tasosgemah, I get a crash instantly in Battle for Naboo if `SuperscaledReads = False` when using 'Rosalie's Mupen GUI' with ParaLLEl. That option doesn't seem to be exposed in this libretro core, though, and it happens immediately when starting the game rather than when starting a level, so I don't know if it's related.

**Comment by Tasosgemah** [comment] 2022-06-27 04:19
The parallel core is outdated and old.

Can you use the current mupen plus next with the parallel rsp/rdp options?

**Comment by Tynach** [comment] 2022-06-29 23:47
> The parallel core is outdated and old.
> 
> Can you use the current mupen plus next with the parallel rsp/rdp options?

@Tasosgemah, I thought it was clear that's what I meant by 'the Libretro core'. If I select the parallel RSP/DSP plugins within RetroArch (using version `9beacb2` of 'Mupen64Plus-Next'), it crashes instantly no matter what game or options I choose, because my Linux distribution uses Ubuntu 20.04 as a base and therefore the version of RetroArch I'm using is 1.7.3.
