### ISSUE TITLE
Threaded renderer disables input poll

### ISSUE THREAD

**Issue by rtomasa** [libretro/mupen64plus-libretro-nx#483] opened 2023-03-15 23:55 UTC
Hi,

I'm creating a new libretro frontend and I noticed that when setting ThreadedRenderer = True, the core stops calling retro_set_input_poll, winch prevents the inputs from working among other things like input hotplug detection.

As per libretro API documentation, the call is required: _During retro_run(), input_poll_evt callback must be called at least once._

Thanks

**Comment by m4xw** [comment] 2023-03-16 02:31
Threaded Renderer relies on early frame polling in the frontend, otherwise depending on the platform you run into compat issues when invoking poll_cb from a thread (android f.e.) tho technically it works for most of them. So i rely on the frontend to set it before calling retro_run

**Comment by m4xw** [comment] 2023-03-16 02:31
https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/libretro/libretro.c#L913-L916

**Comment by m4xw** [comment] 2023-03-16 02:33
Note that i am up for considerations tho, but just implement that env cb :P 
Theres a few like that https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/libretro/libretro.c#L647 is crucial as well otherwise your audio may deadlock depending on your impl

**Comment by rtomasa** [comment] 2023-03-16 09:27
Ohhh thanks for pointing to these methods. I now see that these are retroarch specific in retroarch.h and not part of the libretro.h. Now I understand why some cores were issuing some "unknown" retro env commads. I was getting crazy on this and was because they were in a separated file.

Many thanks, I will implement these callbacks too in my frontend. Feel free to close the issue.

**Comment by rtomasa** [comment] 2023-03-16 09:58
BTW this is a bit unrelated but when using threading and executing retro_unload_game I'm getting a segfault. Do I need to clear stop something else before calling this method? Not happening in any other core that I tested.

**Comment by rtomasa** [comment] 2023-03-16 11:00
I was successfully able to implement RETRO_ENVIRONMENT_GET_CLEAR_ALL_THREAD_WAITS_CB but for some reasson RETRO_ENVIRONMENT_POLL_TYPE_OVERRIDE is never call wen the condition for both are RDP_PLUGIN_GLIDEN64 && EnableThreadedRenderer. Maybe I'm missing something...

**Comment by m4xw** [comment] 2023-03-16 12:00
> Ohhh thanks for pointing to these methods. I now see that these are retroarch specific in retroarch.h and not part of the libretro.h. Now I understand why some cores were issuing some "unknown" retro env commads. I was getting crazy on this and was because they were in a separated file.
> 
> Many thanks, I will implement these callbacks too in my frontend.

Tbh i try to avoid them, but its either that or compile time hacks so i went with that...

I tried to get them into the spec proper because i foresaw these issues ages ago but oh well, here we are



> I was successfully able to implement RETRO_ENVIRONMENT_GET_CLEAR_ALL_THREAD_WAITS_CB, but for some reason RETRO_ENVIRONMENT_POLL_TYPE_OVERRIDE is never called when the condition for both are RDP_PLUGIN_GLIDEN64 && EnableThreadedRenderer. Maybe I'm missing something...

OH LOL
![image](https://user-images.githubusercontent.com/13141469/225610045-5bcf0b63-5a7f-47fd-8005-d3569fd0f0b1.png)

I placed it RIGHT BEFORE, kek. Thats probably why it stopped working on some point........... i recall some stupid shit. Thanks for pointing that out. I double checked that long ago but for some reason didnt see that, so i thought it was a RA regression.........

**Comment by m4xw** [comment] 2023-03-16 12:04
Fixed in https://github.com/libretro/mupen64plus-libretro-nx/commit/bcf62910187fd421ef69ae6830af381f075a818c

**Comment by rtomasa** [comment] 2023-03-16 12:49
Gosh, I was looking at that line in your code and did not realize on the order either 😆

**Comment by m4xw** [comment] 2023-03-16 12:49
That makes me feel slightly better ;)

**Comment by m4xw** [comment] 2023-04-28 09:29
I guess this can be closed

**Closed by m4xw** 2023-04-28 09:29 UTC
Labels: invalid, information
