### ISSUE TITLE
Ocarina of Time - Epona HUD showing up when it shouldn't

### ISSUE THREAD

**Issue by tdeeb** [libretro/mupen64plus-libretro-nx#350] opened 2021-06-20 02:53 UTC
Last week there was an OOT 100% race between two Twitch Plays channels, both using Retroarch 1.9.3 with the Mupen64Plus-Next core. One stream was run on Windows 10 and another on Linux Mint 20.1, and both occassionally experienced this odd Epona HUD bug.

I found a clip of it happening [here](https://clips.twitch.tv/SpeedyObeseHerbsBleedPurple-4Ozi8A4R5ixvW9gA). This is just one instance of it occurring, but it was present for a lot of the run and I'm not sure exactly how to trigger or remove it. I also couldn't find any bug reports on this. I've personally experienced this issue in an OOT ROM hack before but shrugged it off, thinking it was a problem with the hack.

Here are some of the core settings used in both streams:

- **CPU Core**: Dynarec
- **RDP**: GLideN64
- **RSP**: HLE
- **Aspect Ratio**: Original (4:3)
- **Native Resolution Factor**: OFF
- **Threaded Renderer**: OFF
- **Framebuffer Emulation**: ON
- **Depth buffer to RDRAM**: Software
- High-res and custom textures are off
- **Framerate**: Original
- **Ignore emulated TLB Exceptions**: Always Ignore TLB Exceptions (for Dynarec bug)

Another important thing to note is savestates were used heavily throughout the runs, and **Don't Overwrite SaveRAM on Loading State** was toggled ON. If there are any important settings that may be related to this that I missed, let me know and I can get the values of them. Thanks in advance!

**Comment by m4xw** [comment] 2021-06-22 13:54
Dupe of https://github.com/libretro/mupen64plus-libretro-nx/issues/180 due to Ignored TLB
A fix for this has been confirmed but not yet released, u may find it somewhere in the thread

**Closed by m4xw** 2021-06-22 13:54 UTC
