### ISSUE TITLE
After 16baae7 graphics are broken using GLES2

### ISSUE THREAD

**Issue by shantigilbert** [libretro/mupen64plus-libretro-nx#99] opened 2019-09-18 04:07 UTC
After this commit 16baae7 all the graphics on games look cut-off or some don't show at all, Here is a short video to show the problem.

https://youtu.be/6oYoRE0gkFw

I am compiling wit these options:

`platform=AMLG12 GLES=1 FORCE_GLES=1 HAVE_NEON=1 WITH_DYNAREC=arm`
and 
`platform=AMLGX GLES=1 FORCE_GLES=1 HAVE_NEON=1 WITH_DYNAREC=arm`

before this commit everything worked great.

**Comment by m4xw** [comment] 2019-09-18 08:36
I am aware that some new upstream bugs got introduced through that commit, can you try the experimental branch and see if this issue persists?

**Comment by m4xw** [comment] 2019-09-18 11:40
Also lol, that looks funky.
I think I might do a rebase on master and dev and reorder some commits, will need a force push but that way I can split the fixes and update pulls since it currently seems to cause a bunch of Issues.
Will need to wait for feedback on the experimental branch.

**Comment by m4xw** [comment] 2019-09-18 11:43
https://github.com/libretro/mupen64plus-libretro-nx/commit/16baae76c75e434d161b4974c1bcc1cca6db9657#diff-d6cf9c3bcdecce1fd58da0838f7a47adR614-R615

Might be this

**Comment by Tatsuya79** [comment] 2019-09-18 12:03
No issue on 16d9692 win 7 nvidia PC glcore.
Same with default options.

![Mario Kart 64 (USA)-190918-135950](https://user-images.githubusercontent.com/6266038/65146858-1acc1580-da1d-11e9-94cc-0748b7175a0c.jpg)

**Comment by shantigilbert** [comment] 2019-09-18 14:59
@m4xw I will try the latest from the experimental branch and report back.

**Comment by hhromic** [comment] 2019-09-18 18:33
Just tested on RPI3B+ with KMS/DRM/GLES2 using latest `develop` branch and all default core options, all looks normal here.

**Comment by shantigilbert** [comment] 2019-09-18 21:24
Maybe it only affects the Amlogic platforms then... Will try to compile using the rpi3 flags

**Comment by 5schatten** [comment] 2019-09-18 22:47
I guess it's related to builds based on libmali. I have the same glitches here on a Khadas VIM with Mali 450 & disabling GLES3 fixed it somewhat for a VIM 3 with Mali G52.

**Comment by shantigilbert** [comment] 2019-09-19 00:29
@m4xw Experimental branch (I tried latest git) has the same problem. Can't compile with RPI3 flags here, but Amlogic, AMLGX and AMLG12 platforms all have this problem.

**Comment by m4xw** [comment] 2019-09-19 09:15
It's likely to be a issue with the changed shaders then.
I have a amlogic at home.. but it's not setup for dev yet, so it might take a fair while until i get to fix it :/

**Comment by m4xw** [comment] 2019-09-19 09:16
Also I will likely close this and the other issues and create a regression meta issue.

**Comment by spielvan** [comment] 2019-09-19 13:37
@m4xw  first congratulations for the great work you have done and just to report that I have the same problem with the image of the games cutting the graphics of the games, I used an Android TV Box, MX3-G S912, Open GL 2.0ES and Mali 450.

**Comment by shantigilbert** [comment] 2019-09-19 17:08
@m4xw Thanks, take your time, in the meantime I can use the one that works :)

**Comment by m4xw** [comment] 2019-09-19 17:10
@shantigilbert  👍 
@spielvan Screenshot/Picture please

**Comment by spielvan** [comment] 2019-09-20 18:06
@m4xw 

![Screenshot_2019-09-20-13-43-49](https://user-images.githubusercontent.com/17939556/65348631-07a17d00-dbb8-11e9-9f32-ab75ee0e35e4.png)
![Screenshot_2019-09-20-13-43-54](https://user-images.githubusercontent.com/17939556/65348638-096b4080-dbb8-11e9-81a2-f47cad28fe44.png)

**Comment by 5schatten** [comment] 2019-09-21 08:54
I tested MarioKart64 on my Rk3399 & it runs fine -> it also uses libmali & OpenGL ES3 without any glitches. But the Mali GPU is somewhat different since it's a Midgard gen. T860 & it uses the bsp kernel 4.4.154 while I ran the AMLGX/AMLG12 builds with kernel 5.3.

**Comment by spielvan** [comment] 2019-09-21 16:51
> I tested MarioKart64 on my Rk3399 & it runs fine -> it also uses libmali & OpenGL ES3 without any glitches. But the Mali GPU is somewhat different since it's a Midgard gen. T860 & it uses the bsp kernel 4.4.154 while I ran the AMLGX/AMLG12 builds with kernel 5.3.

if you have Open GL3.0 it will run normally, the problem is with Open GL 2.0 ES which unfortunately is the vast majority yet, I even thought to buy a new android tv box with 64bits and Open GL 3.0 or 3.1 but I think overall my android box will change little so i don't know if it would be worth it.

**Comment by drinfernoo** [comment] 2019-09-24 06:01
Pretty sure I opened a duplicate issue? https://github.com/libretro/mupen64plus-libretro-nx/issues/101

My bad if so 😂

**Comment by 5schatten** [comment] 2019-09-24 10:02
I wouldn't call this GLES2 related but rather libmali. Last time I tested my RK3399 with a recent version it had now the same glitches too but was build with [GLES3 support](https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/Makefile#L277-L279) :thinking:

**Comment by m4xw** [comment] 2019-09-24 10:17
@5schatten I have yet to cross-check it on android, so if u can confirm to me this only happens on mali I will change that.

**Comment by 5schatten** [comment] 2019-09-24 10:31
I have to rebuild a RPi2/3 image and will check again. But since I had these glitches on a Khadas VIM, VIM 3 & RockPro64 which use a Mali 450, T860 & G52 I suspect it's related to them.

**Comment by m4xw** [comment] 2019-09-24 10:45
Pi already has been tested but feel free to verify results
https://github.com/libretro/mupen64plus-libretro-nx/issues/99#issuecomment-532810993

**Comment by 5schatten** [comment] 2019-09-24 14:38
@m4xw 
Maybe it's an upstream issue :thinking:  https://github.com/gonetz/GLideN64/issues/2089

**Comment by m4xw** [comment] 2019-09-24 14:40
@5schatten I am aware, this all started with https://github.com/libretro/mupen64plus-libretro-nx/commit/16baae76c75e434d161b4974c1bcc1cca6db9657
Likely the shader changes but I didn't get around trying changes yet.

**Comment by m4xw** [comment] 2019-09-28 17:19
hey @shantigilbert can you try with shadercache off?

**Comment by shantigilbert** [comment] 2019-09-28 18:56
I can in a few hours, but is that a compilation flag/option or a libretro option?

**Comment by m4xw** [comment] 2019-09-28 19:07
It's a core option that shouldn't have much effect on GLES2 but I want to check smth

**Comment by shantigilbert** [comment] 2019-09-28 19:21
ok, give me a few hours and I will check it.

**Comment by m4xw** [comment] 2019-09-28 19:39
@shantigilbert I also just pulled in latest master

**Comment by shantigilbert** [comment] 2019-09-29 03:08
Sorry for the delay. 

I pulled latest commits and the problem persists, I disabled "Cache GPU Shaders" and still nothing changed :(

**Comment by shantigilbert** [comment] 2019-09-29 03:15
Also this seems to only affect Mali-450, My Odroid N2 and VIM 3 worked but they use Mali G52.

**Comment by m4xw** [comment] 2019-10-01 10:23
@shantigilbert It got fixed upstream, I updated the develop branch.
Please try!

**Comment by shantigilbert** [comment] 2019-10-01 16:38
@m4xw It seems that fixed it, I can see the racers in Mario Kart! But I could only do a quick test (over VNC), but I can do a proper test after work!  (in about 6 hours)

**Comment by m4xw** [comment] 2019-10-01 16:39
Nice, I will close the issue for now.
Hit me up if issues arise!

**Closed by m4xw** 2019-10-01 16:39 UTC
Labels: bug

**Comment by spielvan** [comment] 2019-10-01 20:29
@m4xw Here ainda continuous or bug do graphic, ainda I was updated and ainda continuous na f818ff2, ainda não tem pra baixar a f77c16f, what do you test and function @ shantigilbert?

**Comment by m4xw** [comment] 2019-10-01 21:11
@spielvan try it, might be a different issue who knows.

**Comment by spielvan** [comment] 2019-10-02 14:57
@m4xw Just to warn, now released the f77c16f tested here and now yes is working normally, thank you.

**Comment by shantigilbert** [comment] 2019-10-02 16:39
@m4xw Just reporting back, everything seems to work fine now and faster too :) except Resident Evil 2, but I think that one has always been broken.

**Comment by m4xw** [comment] 2019-10-02 17:13
Yea don't think that will work with GLES2, too much limitations.

**Comment by shantigilbert** [comment] 2019-10-02 17:55
Yeah it has always been broken, just pointing it out, although it works somehow on Parallel-n64.
