### ISSUE TITLE
Long loading times before content starts for some Platforms

### ISSUE THREAD

**Issue by Ryunam** [libretro/mupen64plus-libretro-nx#40] opened 2019-03-24 00:05 UTC
I am currently testing this core out with the latest code from the GLideN64 branch and I'm noticing really long loading times when starting any content. 
I am not sure if such a delay is normal compared to most other cores which are usually instant, but with this one on my system I am having 1-2 minutes of waiting time after selecting 'Run' before the content actually starts.
This is happening with my usual RA config file as well as with a fresh new one.

**Comment by sweatypickle** [comment] 2019-03-24 00:44
Windows? No it's not normal as it doesn't happen with standalone mupen and GlideN64. However the delay I get I timed at 22-30 seconds above standalone.

**Comment by m4xw** [comment] 2019-03-24 02:03
Dont report issues for features until they are finished, unless I ask for it.

**Comment by Ryunam** [comment] 2019-03-24 07:45
Since you had distributed the core on Twitter, I thought this would be open and useful for reporting such things. Nevermind then.

**Comment by m4xw** [comment] 2019-03-24 14:39
We are not at that stage yet.
Also I am like the first guy to notice the issues, do you really think I wouldn't notice increased load time?

**Comment by Ryunam** [comment] 2019-03-24 14:54
It is not my intention to stir up an argument, so would you perhaps drop this unnecessarily aggressive act?

Second, as explained above I was under the impression that since you had distributed a build of this same core in a public fashion it would be perfectly reasonable to report and track ANY existing issue here: a lot of people do it and it can be beneficial for development. 
In fact, I can see that other threads have been opened here already to document either feature requests (the native resolution aspect, for example) or bugs, so I still do not really understand why you felt the need to close mine and get all authoritarian on this.

I can assure you it wasn't clear that reporting even something like an extended load time - a perfectly legitimate thing to report, even if you're actually the first guy to notice - was so frowned upon. Once again, nevermind.

**Comment by m4xw** [comment] 2019-03-25 10:08
@Ryunam I didn't want to be percieved as aggressive, in fact it's far from it (for my terms), so excuse me for that.
I am just really straight forward, also I didn't want to close the Issue without giving you a minimalistic explanation.
Issues are welcome, but the 2 specific issues you posted, I am well aware of and these are already in progress of being solved.
I mostly work on my internal tracker anyway.

**Comment by m4xw** [comment] 2019-05-20 16:06
Re-opening the Issue since it still happens on some platforms.
@mudlord didn't you say it didnt happen on newer gcc vers?
Weirdly enough I have this Issue not on Android aarch64 but on aarch32, yet toolchain ver should be the same (4.9).
Doesn't happen on Switch either.

**Comment by mudlord** [comment] 2019-05-20 16:48
ill have to check again what version.

**Comment by m4xw** [comment] 2019-05-20 16:50
Might be a issue with a minor revision

**Comment by Tasosgemah** [comment] 2019-06-28 14:48
Issue appears on both Windows 7 and 10. All roms take about 12 seconds before they load.

**Comment by m4xw** [comment] 2019-06-28 14:49
@Tasosgemah try noise emu off

**Comment by Tasosgemah** [comment] 2019-06-28 14:52
Whoa, fast reply!

Yes, turning off noise emulation fixes this issues. But are there any regressions by turning this feature OFF?

**Comment by m4xw** [comment] 2019-06-28 14:53
Its required for a bunch of stuff

**Comment by Tasosgemah** [comment] 2019-06-28 15:00
Ah yes. Mario's teleport effect in Mario 64 is affected and the Nintendo logo in Cruisin USA's intro.

Those are the two instances of noise effects i remember.

Any chance this issue can be fixed later on without turning this effect OFF?

Though i could still use the old mupen core for the games that use these effects.

**Comment by m4xw** [comment] 2019-06-28 15:02
> Any chance this issue can be fixed later on without turning this effect OFF?

Otherwise this Issue would be closed, lol.

**Comment by mudlord** [comment] 2019-07-03 06:29
You'd think Gonetz would rewrite it to do it on the GPL like I did in the past.

But nooooooooooooooooooooooooo.....thats too much to ask.

**Comment by mudlord** [comment] 2019-09-05 08:51
No I did a fix, see pull request.

**Comment by m4xw** [comment] 2019-09-05 11:05
Fixed in #93

**Closed by m4xw** 2019-09-05 11:05 UTC
Labels: internally fixed

**Comment by Ryunam** [comment] 2019-09-05 13:39
Thanks a lot!

**Comment by Tasosgemah** [comment] 2019-09-05 23:04
Thanks, can't wait to test it.

Is there a version with this fix along with it? https://github.com/libretro/mupen64plus-libretro-nx/issues/86
