### ISSUE TITLE
Corrupt graphics for some games on Intel HD Graphics

### ISSUE THREAD

**Issue by luigiplus** [libretro/mupen64plus-libretro-nx#109] opened 2019-10-07 21:56 UTC
the current mupen64plus-Next version (1.0 f77c16f) and the previous one or 2 began to show problems in  GL driver and  glcore   in the following titles:

![Indiana Jones and the Infernal Machine (USA)-191007-211303](https://user-images.githubusercontent.com/32247691/66349227-4e30fe80-e950-11e9-8dd7-74dd12f19ca0.png)
![International Superstar Soccer 64 (Europe)-191007-211443](https://user-images.githubusercontent.com/32247691/66349229-4ec99500-e950-11e9-84c8-bf0b26e70e4e.png)
![Killer Instinct Gold (USA)-191007-213039](https://user-images.githubusercontent.com/32247691/66349232-4f622b80-e950-11e9-920c-4dd2b5bb1f8f.png)
![Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It)-191007-211858](https://user-images.githubusercontent.com/32247691/66349237-51c48580-e950-11e9-9f33-13931fa63c6e.png)
![Star Wars - Rogue Squadron (USA)-191007-212237](https://user-images.githubusercontent.com/32247691/66349240-55f0a300-e950-11e9-87d5-b16b9f8e805c.png)
![Star Wars Episode I - Battle for Naboo (USA)-191007-212525](https://user-images.githubusercontent.com/32247691/66349241-55f0a300-e950-11e9-963c-95ca5ea70474.png)
![Turok 2 - Seeds of Evil (Europe) (Esp)-191007-212712](https://user-images.githubusercontent.com/32247691/66349243-56893980-e950-11e9-9d25-b48079d23b5b.png)

core options:
mupen64plus-169screensize = "640x360"
mupen64plus-43screensize = "320x240"
mupen64plus-alt-map = "False"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableNativeResTexrects = "False"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rspmode = "HLE"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = 

spec's 
i5 3570, 8gb ram 
windows 10 home x64 1809
intel hd 2500  driver 10.18.10.5069
RetroArch  1.7.9

I remember the version with the fix of long loads worked well with these games in case it helps.

**Comment by m4xw** [comment] 2019-10-07 22:09
While I can't confirm everything, I encountered some new ones..
@fzurita do you know Any of these with fz?

**Comment by fzurita** [comment] 2019-10-07 23:01
I tried all those games with the latest GLideN64 in fz except for the second which I have no idea which one it is. I don't have any of those issues.

**Comment by fzurita** [comment] 2019-10-07 23:05
Although, I did run into a new one. The transition animation is buggy in Rayman 2. It looks like we are using am incorrect size frame buffer somewhere.

**Comment by luigiplus** [comment] 2019-10-07 23:15
I found another one in Excitebike 64
![Excitebike 64 (USA)-191007-210804](https://user-images.githubusercontent.com/32247691/66355695-19c53e80-e960-11e9-92a3-12c4a3daf82c.png)

sorry for not putting the written titles
the soccer game is International Superstar Soccer 64 and the last one is turok 2

**Comment by fzurita** [comment] 2019-10-07 23:17
I was able to identify all but the 2nd one from the buggy screenshots :)

**Comment by m4xw** [comment] 2019-10-07 23:36
@fzurita so no luck?
From his specs this should run on 3.3 core profile.

**Comment by fzurita** [comment] 2019-10-07 23:46
I'm unable to reproduce the issues with fz. This includes the shield tv that runs the 3.3 opengl profile.

**Comment by m4xw** [comment] 2019-10-07 23:54
This is getting weird.
Probably some shenanigans with my gl state machine.

**Comment by m4xw** [comment] 2019-10-07 23:54
Thanks for testing.

**Comment by fzurita** [comment] 2019-10-08 00:44
How does the threaded video work in libretro? Is it doing opengl calls on a separate thread?

**Comment by luigiplus** [comment] 2019-10-08 02:45
more testing:
logo donkey kong
![Donkey Kong 64 (Europe) (En,Fr,De,Es)-191008-013817](https://user-images.githubusercontent.com/32247691/66363184-49367400-e97d-11e9-8547-3bcf618806a5.png)

Kirby 64 
![Kirby 64 - The Crystal Shards (Europe)-191008-015023](https://user-images.githubusercontent.com/32247691/66363213-61a68e80-e97d-11e9-8a42-e376ca5a962e.png)
Mario Tennis
![Mario Tennis (USA)-191008-025223](https://user-images.githubusercontent.com/32247691/66363232-7551f500-e97d-11e9-87ae-e80db7bc49ac.png)
vrally edition 99
![V-Rally Edition 99 (USA)-191008-021702](https://user-images.githubusercontent.com/32247691/66363255-8bf84c00-e97d-11e9-8cc3-c2906dc41d36.png)


"-1080 TenEighty Snowboarding (Japan, USA) (En,Ja).n64" ok
"-Banjo-Kazooie (E) (M3 ok
"-Banjo-Tooie (E) [!](.Z64) ok
"-Blast Corps (USA).n64" ok
"-Body Harvest (USA).zip" ok
"-Bomberman 64 (USA).n64" ok
"-Bomberman Hero (Europe).zip" ok
"-Buck Bumble (USA).zip" ok
"-Conker's Bad Fur Day (USA).n64" ok
"-Diddy Kong Racing (USA) (En,Fr).n64" ok
"-Donkey Kong 64 (Europe) (En,Fr,De,Es).n64"   logo problem, gameplay ok
"-Doom 64 (USA).n64" ok
"-Excitebike 64 (USA).n64"  corrupt graphics
"-F-1 World Grand Prix (USA).n64" ok
"-F-Zero X (USA).n64" ok
"-Goemon's Great Adventure (USA).zip" ok
"-GoldenEye 007 Spa SkanderX.z64" ok
"-Hybrid Heaven (Europe) (En,Fr,De).zip" ok
"-Indiana Jones and the Infernal Machine (USA).n64" corrupt graphics
"-International Superstar Soccer 64 (Europe).n64" corrupt graphics
"-Killer Instinct Gold (USA).n64" corrupt menus, gameplay ok
"-Kirby 64 - The Crystal Shards (Europe).n64" corrupted menus

"-Legend of Zelda 2 - Majora's Mask (E) [!].z64" ok
"-Legend of Zelda, The - Ocarina of Time (USA).n64"  white screen menu

"-Mario Kart 64.v64" ok
"-Mario Party (USA).n64" ok
"-Mario Tennis (USA).n64" corrupt graphics

"-Mischief Makers (USA).n64" ok
"-Mission Impossible.n64" ok
"-Mystical Ninja Starring Goemon (USA).n64" ok
"-Ogre Battle 64 - Person of Lordly Caliber (USA) (Rev A).zip" ok
"-Operation WinBack (Europe) (En,Fr,De,Es,It).zip" ok
"-Paper Mario.z64" ok
"-Perfect Dark (USA).n64" ok
"-Pilotwings 64 (USA).n64" ok
"-Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).n64" corrupt graphics

"-Shadow Man (USA).n64" ok
"-Sin and Punishment.z64" ok
"-Star Fox 64 (USA).n64" ok
"-Star Wars - Shadows of the Empire (USA).n64"
"-Super Mario 64 (USA).n64" ok
"-Super Smash Bros. (USA).n64" ok
"-Turok 2 - Seeds of Evil (Europe) (Esp).n64" corrupt graphics

"-V-Rally Edition 99 (USA).n64" corrupt menu selection cars

"-Wave Race 64 (USA).n64" ok
"-Yoshi's Story (Europe) (En,Fr,De).n64" ok

**Comment by m4xw** [comment] 2019-10-08 10:27
So, on my side, no issues in Indiana Jones, Star wars and KI, thats on Switch with 4.3 compat OpenGL.
Kirby I can replicate different Issues.
Maybe a scissoring issue?
Hmm. I know some only happen with fbemu off like that..
Weird.

**Comment by m4xw** [comment] 2019-10-08 10:29
Oh I just saw you use Intel HD garbage.
Lemme try smth

**Comment by m4xw** [comment] 2019-10-08 10:32
@luigiplus Try this.

[mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3701965/mupen64plus_next_libretro.zip)

**Comment by m4xw** [comment] 2019-10-08 10:38
@fzurita It just moves everthing to the rendering thread.
All stuff still happens on that thread (afaik..)
It should've been implemented simliar to how u did it, but it's too late for that in RA, currently.
We will work on a proper API for such a impl. for the v2 spec.

The Issue here is likely that the core wasn't built with the `CORE` define which changes the OpenGL context requested + some statemachine stuff.
So call that a bunch of undefined behaviour.
We have that define for all platform but Windows (and on Switch we use the define because we wan't some statemachine behaviour but we don't request Core context there, because that doesnt seem to work properly with hb drivers for me right now)

**Comment by m4xw** [comment] 2019-10-08 10:39
Intel HD really has been picky about that in my experience...

**Comment by luigiplus** [comment] 2019-10-08 14:00
I have finished testing everything but they follow the same results.

**Comment by m4xw** [comment] 2019-10-08 14:17
very odd.
I will try to replicate.

**Comment by Cee123** [comment] 2019-10-09 08:05
I can confirm these glitched graphics issues also occur on Odroid Xu4, N2 and Raspberry Pi 3b. :(

**Comment by m4xw** [comment] 2019-10-09 09:42
@luigiplus try this
[mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3706634/mupen64plus_next_libretro.zip)

**Comment by m4xw** [comment] 2019-10-09 10:00
@luigiplus Try this too 
[experimental_mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3706719/experimental_mupen64plus_next_libretro.zip)
Tell me which works better.

**Comment by luigiplus** [comment] 2019-10-09 15:51
@m4xw  the experimental mupen: same result as the previous ones.
In the other mupen, all corrupt games that name on the list work except iss64 same result. 
Long loads when starting the core and blurry text in general for all games ( GL driver and glcore ).
some screenshot blurry:
![Donkey Kong 64 (Europe) (En,Fr,De,Es)-191009-152750](https://user-images.githubusercontent.com/32247691/66497801-f069f700-eab4-11e9-95dd-4926af47154b.png)
![Indiana Jones and the Infernal Machine (USA)-191009-160409](https://user-images.githubusercontent.com/32247691/66497802-f069f700-eab4-11e9-9fe8-d4cd5e8b485c.png)

**Comment by m4xw** [comment] 2019-10-09 15:53
Blurry text is because your resolution.
Long loading times because a missing fix (its a older core).
So it's still part of the recent regressions..

**Comment by m4xw** [comment] 2019-10-09 15:58
I will need to do some bisecting, will have lots of builds to test...
Will need a few days tho since busy IRL

**Comment by m4xw** [comment] 2019-10-14 18:21
Closed in favor of #117

**Closed by m4xw** 2019-10-14 18:21 UTC

**Comment by m4xw** [comment] 2019-10-22 14:37
@luigiplus I pushed a mitigation that should fix some cases that bug around on lowest resolution.
The issue itself is not resolved tho, so I will need to revisit it.
Would be great if u can test some of these with this build (last develop commit)
However this will downscale from 640x resolution, so it will not help performance.

https://m4xw.net/nextcloud/index.php/s/f2BMjEdEK7R69ys

**Comment by luigiplus** [comment] 2019-10-22 16:30
Ok, I've tested all the games and the image doesn't look blurry anymore. Some screenshots:
![Indiana Jones and the Infernal Machine (USA)-191022-165050](https://user-images.githubusercontent.com/32247691/67307829-0635de00-f4f1-11e9-9827-1808c56c0b37.png)
![Donkey Kong 64 (Europe) (En,Fr,De,Es)-191022-170357](https://user-images.githubusercontent.com/32247691/67307834-07670b00-f4f1-11e9-8ac6-7e8e9f345804.png)

![V-Rally Edition 99 (USA)-191022-165217](https://user-images.githubusercontent.com/32247691/67308176-983de680-f4f1-11e9-9a2d-0e7001e463a4.png)

**Comment by m4xw** [comment] 2019-10-22 16:37
@luigiplus Yea because they are scaled down, this is a bug but it will need some more consideration.
I will raise the Issue upstream later, I hope this will do for now.
