### ISSUE TITLE
Yoshis Story broken Graphics

### ISSUE THREAD

**Issue by BParks21** [libretro/mupen64plus-libretro-nx#97] opened 2019-09-10 08:44 UTC
Latest core version in game level backgrounds are broken.  No settings in the core seem to effect this. 

![Yoshi's Story (USA) (En,Ja)-190910-042903](https://user-images.githubusercontent.com/12180630/64598405-a989c400-d385-11e9-8394-02f6de2c35f5.png)
![Yoshi's Story (USA) (En,Ja)-190910-042912](https://user-images.githubusercontent.com/12180630/64598413-ab538780-d385-11e9-9cc4-a1bea0ae79e4.png)

**Comment by m4xw** [comment] 2019-09-10 08:56
Dupe of #86

**Closed by m4xw** 2019-09-10 08:56 UTC

**Comment by m4xw** [comment] 2019-11-29 11:11
This upstream regression seems to be fixed with bgmode OnePiece now again!
