### ISSUE TITLE
Instability/Corruption likely related to Texture cache size on low end devices.

### ISSUE THREAD

**Issue by alessandropaggi** [libretro/mupen64plus-libretro-nx#28] opened 2019-02-25 08:17 UTC
Hello,
I've noticed that on RetroPie after 20 minutes or so the emulator starts glitching and then it crashes.
I tried disabling the framebuffer emulation, but the problem remains.

**Comment by m4xw** [comment] 2019-02-25 09:55
ROM, distribution details, git hash, crash dump?

**Comment by m4xw** [comment] 2019-02-25 09:56
Likely related to tex cache size, but that would mean wontfix until gliden update.

**Comment by m4xw** [comment] 2019-02-25 09:57
cc @hhromic

**Comment by alessandropaggi** [comment] 2019-02-25 22:06
The git hash is

1c2029abcf15b486a5e7ae5517521c1559f31d37

I installed lr-mupen64plus-next on my RetroPie following the instructions given in

https://retropie.org.uk/forum/topic/21093/lr-mupen64plus-next-experimental-scriptmodule-for-testing

The rom I tested it with is Mario Kart 64, the output of runcommand until the crash is in https://pastebin.com/cvqDYLMi

**Comment by hhromic** [comment] 2019-02-25 22:17
@alessandropaggi thanks for the log and the info. I will investigate.
It always happen after ~20 minutes of running the game? no matter what you do in the game?

**Comment by alessandropaggi** [comment] 2019-02-25 22:32
If I let the demo mode run, I reached 30 minutes without the crash occurring. But if I start playing (regardless of what I do) at about 21-22 minutes the emulator starts chopping, the sprites become black boxes, everything starts freezing, and if I am lucky I am able to close the emulator before the whole thing crashes and I have to turn it off and on again.
I add that this bug does not occur with the current release of the standalone mupen64plus on RetroPie. Someone in the RetroPie forum suggested that this can be due to an issue with the gliden64 version included in lr-mupen64plus-next.

**Comment by m4xw** [comment] 2019-02-25 22:39
Yea sounds like tex cache size to me (tho that only mitigates)

Try changing that line https://github.com/libretro/mupen64plus-libretro-nx/blob/mupen_next/GLideN64/src/Textures.cpp#L530

To 1500 +/- a few 500's, see if you can get a val that doesnt crash after longer periods.
I tested it in lylat wars on the solar map, if you see planets going black after 1 minute or so, its too high.
It will start lagging a lot on the solar map then, but no crash.

**Comment by m4xw** [comment] 2019-02-25 22:39
iirc 1500 is used for upstream these days on Pie.

**Comment by hhromic** [comment] 2019-02-25 22:46
Yes, indeed it's 1500 for `VC` in upstream (and 8000 for others):
https://github.com/gonetz/GLideN64/blob/f55283e32fbb7fc4e4eddfc3db566b4f782d2389/src/Textures.h#L103-L107

Shall we backport these values here for the moment and see if that temporarily helps?

**Comment by alessandropaggi** [comment] 2019-02-25 22:48
@m4xw You mean Star Fox 64?

**Comment by m4xw** [comment] 2019-02-25 22:54
@hhromic @alessandropaggi yes and yes

**Comment by m4xw** [comment] 2019-02-25 22:55
Tho i tweaked the libnx val manually, higher than 4k had issues in this gliden ver.

**Comment by hhromic** [comment] 2019-02-26 09:30
@m4xw @alessandropaggi  I left Mario Kart 64 running in the demo mode overnight and didn't crash. I will test playing the game and also test Star Fox 64 as mentioned (hopefully the issue can be reproduced without waiting 20 minutes each time).

If i find the issue, I will manually tweak the cache size to find a sweet spot like @m4xw did for the Switch build. In this case I will send a PR updating the values here in the meantime before the new GlideN64.

Also @alessandropaggi do you have any custom GPU memory split in your RPI setup?
I have the standard settings from RetroPie:

    gpu_mem_256=128
    gpu_mem_512=256
    gpu_mem_1024=256

**Comment by m4xw** [comment] 2019-02-26 10:13
Thanks for taking your time to test it!
Been kinda busy lately.

**Comment by hhromic** [comment] 2019-02-26 17:51
@alessandropaggi I've been running Mario Kart 64 (USA) for a solid hour now (playing and leaving it run alone) and I can't reproduce the issue on my RPI 3B board.  Can you confirm that you are using a large enough GPU memory split as I showed before?

Also, I noticed that you have an ALSA-related error reported in your log, near the end where it crashes. Maybe this is related?

**Comment by hhromic** [comment] 2019-02-26 18:04
Further about the Core Reset segfault, I think it happens when re-initialising the dynarec. The following is the log sequence when first booting a game:
```
[libretro INFO] mupen64plus-next: Initializing 4 RDRAM modules for a total of 8 MB
[libretro INFO] mupen64plus-next: Starting R4300 emulator: Dynamic Recompiler
[libretro INFO] mupen64plus-next: Init new dynarec
[libretro INFO] mupen64plus-next: ARM CPU Features:, Half, Thumb, FastMult, VFP, ESDP, NEON, VFPv3, TLS, VFPv4, IDIVa, IDIVt
```

If you reset the core, it crashes just before the "Starting R4300 emulator: Dynamic Recompiler" line:
```
[INFO] Reset.
[libretro INFO] mupen64plus-next: Initializing 4 RDRAM modules for a total of 8 MB
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1007:  4149 Segmentation fault      /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mupen64plus-next/mupen64plus_next_libretro.so --config /opt/retropie/configs/n64/retroarch.cfg "/home/pi/RetroPie/roms/n64/Mario Kart 64 (USA).n64" --verbose --appendconfig /dev/shm/retroarch.cfg
```

Exactly the same in Windows. What do you think @m4xw ?

**Comment by alessandropaggi** [comment] 2019-02-26 18:08
> @alessandropaggi I've been running Mario Kart 64 (USA) for a solid hour now (playing and leaving it run alone) and I can't reproduce the issue on my RPI 3B board. Can you confirm that you are using a large enough GPU memory split as I showed before?

Hello, the GPU settings in my `/boot/config.txt` are the same as yours.

```
gpu_mem_256=128
gpu_mem_512=256
gpu_mem_1024=256
```

**Comment by m4xw** [comment] 2019-02-27 10:39
@hhromic that reset bug happens since forever.
I am sure it happened to me with Cached too, at least in old mupen.
If you gave me correct informations I know where to search ;)

**Comment by hhromic** [comment] 2019-02-27 11:14
@m4xw I will be doing some debugging about the reset issue later today and give more precise info.

@alessandropaggi Can you tell us more about your setup? Are you using HDMI? AV-output? Latest version of RA (1.7.6) ?  I think we need to take your ALSA-related error out of the way. At some point did you reset the core in RA (that can explain the "Reset" log message).

**Comment by hhromic** [comment] 2019-02-27 15:22
@m4xw I opened now issue #31 to track the reset crash. I captured now a couple of GDB stack traces for more information about the problem. I can confirm that it crashes with all but the *cached interpreter* cpu type.  I will be investigating more to see if we can pin-point the problem. Probably is something small but tricky to find :)

**Comment by alessandropaggi** [comment] 2019-02-27 18:47
> @m4xw I will be doing some debugging about the reset issue later today and give more precise info.
> 
> @alessandropaggi Can you tell us more about your setup? Are you using HDMI? AV-output? Latest version of RA (1.7.6) ? I think we need to take your ALSA-related error out of the way. At some point did you reset the core in RA (that can explain the "Reset" log message).

I use HDMI with RA 1.7.6. I did reset the the core just after it started glitching, If you want I can take another `runcommand.log` without resetting, letting the core crash.

**Comment by hhromic** [comment] 2019-02-28 11:03
@alessandropaggi ah, so it crashed because of the reset bug not the glitch. Good to know.
Have you seen it crash because of the gfx glitch? Can you do that then? just let it run until it crashes.

**Comment by m4xw** [comment] 2019-02-28 11:03
@hhromic The symptoms are usually the core bugging out, just "Close content" is enough to crash it then.
Doesn't need to be reset.

**Comment by m4xw** [comment] 2019-02-28 11:04
At least thats how it used to be.
Can you get him a build with 1500 tex size to test?

**Comment by hhromic** [comment] 2019-02-28 11:07
> The symptoms are usually the core bugging out, just "Close content" is enough to crash it then. Doesn't need to be reset.

Didn't try that, I will check it out and if I get a more informative stack trace will post it in the other issue.

> Can you get him a build with 1500 tex size to test?

Sure, I already built a binary with that change. Actually after some hours of testing all seems working the same for me, so was planning on sending a PR. Will post the binary here first.

**Comment by alessandropaggi** [comment] 2019-02-28 11:07
> @alessandropaggi ah, so it crashed because of the reset bug not the glitch. Good to know.
> Have you seen it crash because of the gfx glitch? Can you do that then? just let it run until it crashes.

Sure thing, I will when I get home this evening and send you the crash dump.

**Comment by hhromic** [comment] 2019-02-28 11:26
@alessandropaggi I built now a version of mupen64plus-next that has 1500 as the max cache size for textures. Find it here: [mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/2914721/mupen64plus_next_libretro.zip)

Can you place it in `/opt/retropie/libretrocores/lr-mupen64plus-next` and test it as well?
You might want to backup the existing core if you don't want to rebuild the original one.

**Comment by alessandropaggi** [comment] 2019-02-28 20:47
Ok, this time I have some more informations.
I kept playing in the same Mario Kart cup for about 30 minutes, and the bug did not occur. Then I changed cup, and after about 3 minutes the bug happened. At first the emulator hangs, the sound goes off, and the sprites start messing up. The emulator becomes very choppy, but I kept playing and noticed that the system does not actually crash, but after a while keeps running more or less chopping, without sound and with several graphical glitches like weird sprites and random slowdowns and speedups of the emulation.
This is the `runcommand.log` dump:
https://pastebin.com/3wxpaFKU
The only error I notice is the `[ALSA]: Unknown error occurred (Input/output error)` at the end, so could it really be a sound error that triggers the graphical glitches?

**Comment by alessandropaggi** [comment] 2019-02-28 23:28
> @alessandropaggi I built now a version of mupen64plus-next that has 1500 as the max cache size for textures. Find it here: [mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/2914721/mupen64plus_next_libretro.zip)
> 
> Can you place it in `/opt/retropie/libretrocores/lr-mupen64plus-next` and test it as well?
> You might want to backup the existing core if you don't want to rebuild the original one.

I tried this new version, and I was able to play over 40 minutes two different Mario Kart cups without the bug happening.

**Comment by m4xw** [comment] 2019-02-28 23:53
Sounds good, thanks for testing

**Comment by hhromic** [comment] 2019-03-01 11:41
@alessandropaggi thanks for testing!  so you can 100% confirm that the 1500-capped binary didn't crash for you in a good amount of gameplay time? And also you don't notice new glitches?

@m4xw I couldn't reproduce the glitches myself using a vanilla minimal RetroPie, so finding the biggest stable value seems very subjective. In my case I would "find" the current value 15000 for example that doesn't work for @alessandropaggi. Perhaps his setup has something else we are not seeing.

I was thinking on how about adding a configurable option for this? "Max Cache Size", with a default depending on the platform but configurable by users in different situations?  I can code this and send a PR if you think is a better approach.

**Comment by m4xw** [comment] 2019-03-01 11:51
@hhromic sure we can make this a core option, I def. had issues with 15k on switch tho and that's quite a bit beefier, so yea, not sure why it works for you honestly :P
Try lylat wars and stay a bit on the galaxy map, you will eventually see the planets turn black - in a matter for seconds.
It's a weird Issue.

**Comment by hhromic** [comment] 2019-03-01 11:55
@m4xw I did try Lylat Wars (the european version of StarFox 64) and left it running for several minutes in the galaxy map without any problems. I just need to start the game and stay in the map right? or I need to play some stages first? I will try again making 1000% sure I'm using a binary with the current 15000 as limit.

Btw, the upstream 1500 limit was already manually investigated in [this commit](https://github.com/gonetz/GLideN64/commit/e9becd4b8a1173e3567b0e2a2a3d9df85e4b424d) for the RPI, so I guess we can safely use the upstream values as defaults.

> rpi: limit m_maxCacheSize to fix texture corruption
> Limit m_maxCachSize to fix texture corruption in Yoshi’s Story. I have
> tested values between 1500 and 3500. Everything >= 1800
> produces texture corruption after a short time.

**Comment by alessandropaggi** [comment] 2019-03-01 12:17
> @alessandropaggi thanks for testing! so you can 100% confirm that the 1500-capped binary didn't crash for you in a good amount of gameplay time? And also you don't notice new glitches?

I cannot exclude that I could eventually crash after playing for a longer time (like two hours or more) but I can confirm that I did not crash in ~45 minutes of playing, while with the old build it was alway crashing in the first ~ 20 minutes. Also I did not notice new additional glitches.

**Comment by hhromic** [comment] 2019-03-01 12:45
@m4xw I did some instrumentalised testing now with the current 15000 limit.

Lylat Wars leave it alone until menu screen, then start game and let it alone until galaxy map screen. At this point, I have these on my stock RPI 3B:

    cacheSize=10726
    gpu=256M
    malloc_total=12M
    malloc=10M
    reloc_total=236M
    reloc=68M

After starting the Corneria stage and letting the game go alone (poor Fox dies two times) and returning back to the galaxy map after the Game Over screen:

    cacheSize=12393
    malloc=10M
    reloc=48M

So still plenty of GPU memory left to spare and the 15000 limit of course is still safe and doesn't glitch.

So I guess making it configurable is indeed the best option to make users happy in different situations. I will be putting together a PR for this soon and we can discuss it more there.

---

Legend of `vcgencmd` output:
gpu: total memory assigned to gpu
malloc_total: total memory assigned to gpu malloc heap
malloc: free gpu memory in malloc heap
reloc_total: total memory assigned to gpu relocatable heap
reloc: free gpu memory in relocatable heap

**Comment by hhromic** [comment] 2019-03-01 13:50
> @hhromic sure we can make this a core option, I def. had issues with 15k on switch tho and that's quite a bit beefier, so yea, not sure why it works for you honestly :P

@m4xw I think a fundamental difference is that the RPI is forced to run with less demanding options. In particular these are always set to disabled (0) or a specific setting:

    frameBufferEmulation.enable
    frameBufferEmulation.copyToRDRAM
    generalEmulation.enableFragmentDepthWrite
    frameBufferEmulation.bufferSwapMode = Config::bsOnColorImageChange

That would explain why the switch loads beefier textures into the GPU and you hit the limit faster?

By the way I'm also planning on make these options configurable (not forced) but instead set the appropiate settings as defaults in compile-time. This way users can change options (at their own risk). This will be particularly useful when the new GlideN64 plugin is ready, because for example FrameBuffer emulation works much better on RPI than the current one and users might want to use it.

I am working on a PR for this here: https://github.com/libretro/mupen64plus-libretro-nx/compare/mupen_next...hhromic:dont-force-options

**Closed** 2019-03-01 15:53 UTC
Labels: legacy bug

**Comment by hhromic** [comment] 2019-03-01 15:57
@alessandropaggi a new core option was added now to configure the max cache size.

You can re-build and re-install the core using the RetroPie scriptmodule to see it. By default on RPI devices it will be set to `1500`, so you should see your issue fixed. You can change this value to `4000` or `8000` (both way lower than the previous hard-coded `15000`) to experiment what works best for you.

Thanks for reporting and testing!

**Comment by alessandropaggi** [comment] 2019-03-01 18:20
> **Edit2:** I checked your log file and indeed you seem to be using the XMB menu driver that loads a number of shaders for the background effect, which may be too much for the poor RPI. Maybe try using the simpler RGUI (I personally like it more to be honest) to confirm this causes the issue even with 256M split.

@hhromic Ok, I will test the old build with the basic GUI.

>a new core option was added now to configure the max cache size.
>You can re-build and re-install the core using the RetroPie scriptmodule to see it. By default on RPI devices it will be set to `1500`, so you should see your issue fixed. You can change this value to `4000` or `8000` (both way lower than the previous hard-coded `15000`) to experiment what works best for you.

@hhromic I will test this new build, and see how the XMB GUI is affecting the results.
Thanks.

**Comment by alessandropaggi** [comment] 2019-03-02 10:19
> **Edit2:** I checked your log file and indeed you seem to be using the XMB menu driver that loads a number of shaders for the background effect, which may be too much for the poor RPI. Maybe try using the simpler RGUI (I personally like it more to be honest) to confirm this causes the issue even with 256M split.

@hhromic I tested the old build with the RGUI, and the glitch did occur, although at a later time mark (~40 minutes).

**Comment by hhromic** [comment] 2019-03-02 10:46
@alessandropaggi then I guess def is something per-setup and making the max texture cache configurable per-user was a good thing to do. Try with diff cache sizes until you find the max that works ok for you. Thanks for testing !

**Comment by alessandropaggi** [comment] 2019-03-02 12:15
> @alessandropaggi a new core option was added now to configure the max cache size.
> 
> You can re-build and re-install the core using the RetroPie scriptmodule to see it. By default on RPI devices it will be set to `1500`, so you should see your issue fixed. You can change this value to `4000` or `8000` (both way lower than the previous hard-coded `15000`) to experiment what works best for you.

I tested the new build with the RGUI, both with `4000` and `8000` max cache size, and reached ~ 45 minutes of play without the glitch occurring.
I have a copule of questions I would like to ask you guys.
1) What is the backdraw of using a low max cache size (~ 1500)?
2) How does the framebuffer emulation factor into this?

**Comment by hhromic** [comment] 2019-03-02 14:25
> I tested the new build with the RGUI, both with 4000 and 8000 max cache size, and reached ~ 45 minutes of play without the glitch occurring.

Sounds good :) thanks for the feedback.

> 1. What is the backdraw of using a low max cache size (~ 1500)?

I'm not the expert there, but here are my 20c. I think for games that need to load many textures, having a small cache means the emulator has to swap them more often from/to the GPU and this means potential hiccups. Also, consider that the size option is in "number of textures" not "bytes size" so there is no universal setting. For instance, you can fit many small textures but few big ones. For this reason you should set the biggest you can empirically. Finally, consider that the current options are based on manually tested numbers by the developers in upstream, so they are probably the best options.

> 2. How does the framebuffer emulation factor into this?

Unfortunately, I recently found out that the FB emulation option doesn't have any effect on Raspberry Pi. It is always disabled no matter what you set the option to. I made a build with this option not forced and when enabling FBemu most games don't run very well (hence why is probably force-disabled). The good news are that it seems to work much better on newer GLideN64 (tested using standalone), so when it makes it to this core, we can allow access to it on RPI.

**Comment by hhromic** [comment] 2019-03-02 14:26
There are other options that are also always forced to disabled. See my previous comment here: https://github.com/libretro/mupen64plus-libretro-nx/issues/28#issuecomment-468670562

**Comment by alessandropaggi** [comment] 2019-03-02 14:55
Ok, I thinks that is all for me.
Thank you guys for the support and the good job. Looking forward for the next release with the update GLideN64 plugin.
