### ISSUE TITLE
EEPROM16K save type needed for Donkey Kong 64 - Tag Anywhere (V5) (U) to save

### ISSUE THREAD

**Issue by Isotarge** [libretro/mupen64plus-libretro-nx#405] opened 2021-11-27 13:33 UTC
This emulator provides a fantastic experience with this ROM hack, with one exception. EEPROM16K save type is not automatically detected, so the game cannot save (without using the savestate feature built into their libretro frontend).

I have filed a PR with upstream https://github.com/mupen64plus/mupen64plus-core/pull/911 just wanted to make this project's maintainers aware that the new ini will need to be pulled from upstream to fix this.

Is there a way we can automatically detect which save type the ROM is using? Perhaps a write to a specific register on the system bus? Adding every single DK64 ROM hack under the sun to the upstream ini feels a bit silly to me, especially since the EverDrive64 can somehow detect it correctly.

**Comment by Jj0YzL5nvJ** [comment] 2021-11-27 18:29
> Without the changes in this PR, it is not possible to exercise the "EEPROM not detected" code-path since Mupen64Plus will always have a 4K EEPROM (unless 16K EEPROM is specified)

https://github.com/mupen64plus/mupen64plus-core/pull/878#issuecomment-867653998

**Comment by m4xw** [comment] 2021-11-29 12:31
Pulling core is on my TODO; I generally always generate the inis then for good practice.
Kinda busy IRL currently so the gliden rebase has been slacking too, been working on some low end perf improvements for the dynarec

**Comment by m4xw** [comment] 2022-01-12 14:18
should be fixed

**Closed by m4xw** 2022-01-12 14:18 UTC

**Comment by Xii-Nyth** [comment] 2022-08-18 21:07
Ive been unable to save even without this rom hack :/ can you not save from a save state?

**Comment by Jj0YzL5nvJ** [comment] 2022-08-20 17:57
mupen64plus-ae/mupen64plus-ae#908

**Comment by Xii-Nyth** [comment] 2022-08-21 00:07
huh weird that its just this game. then again it doesnt save widescreen/story skip but saves sound and chimpy cam, and has a seemingly useless save button in the game.

**Comment by Jj0YzL5nvJ** [comment] 2022-08-21 03:10
Or you use native save or you use savestate. You can't use both, if you use savestate it corrupts the native save.

> huh weird that its just this game.

Actually there are quite a few depending on what you consider "corruption" in your dictionary. The real difference is that in the other games you can "repair" the native save by re-saving again.
My theory is that the game saves only the differential information from the last memory access instead of overwriting the whole "save block" again. Another possibility would be that it gets corrupted by timing issues, [similar to this one](https://github.com/mupen64plus/mupen64plus-core/pull/853#issuecomment-821321920).

**Comment by Xii-Nyth** [comment] 2022-08-21 04:51
Maybe its something do do with the anticheat which bricked the game?

**Comment by Jj0YzL5nvJ** [comment] 2022-08-21 05:04
If that were the case, the error would be reproducible on devices like EverDrive and ROM hacks in real hardware.

**Comment by Xii-Nyth** [comment] 2022-08-21 05:53
Oh didnt know it wasnt, I only use my old n64 for reference when debugging these days

**Comment by turntable97** [comment] 2024-06-13 23:49
I just can't manage to save on a DK64 Widescreen hacked ROM.
How is this possible? Do I need to make a specific setting in RetroArch to make it work?
I'd appreciate any help I can get!

**Comment by Jj0YzL5nvJ** [comment] 2024-06-14 19:25
You must add your ROM hacks to your `mupen64plus.ini` file. Or make a PR (pull request) for said ROM hacks.

**Comment by turntable97** [comment] 2024-06-15 12:35
> You must add your ROM hacks to your `mupen64plus.ini` file. Or make a PR (pull request) for said ROM hacks.

Okay, I'm struggling:
I added a widescreen patch to my "Donkey Kong 64 (U) [!]" and tried to add it to the ini file. 
I scanned the patched rom with Info64 and Project64 to find out the MD5. It differs in both programs. (MD5 and MD5 Hash? Which is needed?)
In the ini file there is a value needed which is in brackets [value] and a RefMD5. 

I hope you can help me!! :) Thanks a lot!

**Comment by turntable97** [comment] 2024-06-15 13:55
Alright:

I added a widescreen patch to my "Donkey Kong 64 (U) [!]" and tried to add it to the ini file.

I managed find the correct values. With a Hexeditor i found the correct MD5 128bit checksum. And I took the "GoodName" from the retroarch log. The CRC values are shown in the ROM information when loading the rom in Project64.

In retroarch\cores\system\Mupen64plus I edited the mupen64plus.ini and listed my hacked rom below the original:

[9EC41ABF2519FC386CADD0731F6E868C]
GoodName=Donkey Kong 64 (U) [!]
CRC=EC58EABF AD7C7169
SaveType=Eeprom 16KB
Players=4
CountPerOp=1
Rumble=Yes

**[FCA204F4E43816D489355D9EDE736D1D]
GoodName=DONKEY KONG 64 (unknown rom)
CRC=1611B29B 3EEF9034
RefMD5=9EC41ABF2519FC386CADD0731F6E868C**

What happens now is everytime I load the game the whole entry seems to be automatically deleted. When I check the INI file after I close the game the entry is completely gone.

Why does that happen?

I hope someone can help me.
Thanks!

**Comment by Jj0YzL5nvJ** [comment] 2024-06-15 15:11
> Why does that happen?

RetroArch thing? I don't know, I don't really use RetroArch/Libretro. I more alike to a lurker when it comes to N64 emulation and I provide support if I'm in the mood.

See: libretro/mupen64plus-libretro-nx#539

In short, change the file attribute to read-only to prevent it from self-restoring.

**Comment by turntable97** [comment] 2024-06-15 16:43
I've managed to make the INI write protected. And it doesn't overwrite when launching the game like before.
But still, it creates and .srm savefile but the saveslots in the menu stay empty.
HELP :'(

**Comment by Xii-Nyth** [comment] 2024-06-27 20:19
Oh turns out in my case the emu I was working with had the wrong save type set and assumed it waasnt the issue since much old emus (1964) had it defaulting to the correct one. Maybe whatever stock mupen config peole grab when making emus is wrong. Not sure how to change this stuff in retroarch since thats all very "put together" but it seems you found the setting in an ini somewhere and set it to read only so it didnt change back. Ive played not tag anywhere but start with lanky and saves and states seem to work fine in RMG... so I guess for the time being might have to use that instead.
