### ISSUE TITLE
Missing textures & models on aarch64

### ISSUE THREAD

**Issue by MichaelMackus** [libretro/mupen64plus-libretro-nx#233] opened 2020-07-12 17:35 UTC
Hello,

I've tried to compile this repo with many different configurations, and none of them seem to work on my Aarch64-based Pinebook Pro. This chip should be supported since it is very similar to the Rock64Pro, which is directly supported, which leads me to think Arm builds are broken entirely ATM. I've tried forcing OpenGLES and also building without, neither seem to work. 

With OpenGL enabled (non GLES) I get a black screen. 

With OpenGLES enabled, it gets further but all games are missing any sort of 3d models - for example, in Mario 64 I can't see Mario's face, only the BG. In Mario Kart 64, I can start a game just fine, but once it starts I just see the 2d background gradient but none of the carts or track (all 3d models seem absent).

I'm successfully running things perfectly with mupen64plus (without retroarch). I believe the default build there uses OpenGL 2, which is supported on this PC (as well as OpenGLES 2).

EDIT: Also, something I forgot to mention, is that I also tried downloading & enabling shaders in retroarch. Trying a few makes no difference. All my other retroarch cores work great such as PCSX, Snes9x, bsnes, and others.

Finally, I am using the Glide64 video plugin. This plugin works great for me in mupen64plus core (non-retroarch).

**Comment by m4xw** [comment] 2020-07-13 09:05
Based on your description probably duplicate of https://github.com/libretro/mupen64plus-libretro-nx/issues/227

> Finally, I am using the Glide64 video plugin. 

Mupen Next doesnt have Glide64

**Closed by m4xw** 2020-07-13 09:05 UTC
