### ISSUE TITLE
The Missing Link crashes when entering house (ISViewer Log Issue)

### ISSUE THREAD

**Issue by krispya** [libretro/mupen64plus-libretro-nx#412] opened 2022-01-10 01:36 UTC
I am trying to play the rom hack The Missing Link: https://www.romhacking.net/hacks/5334/

It currently crashes when I try to enter a house in the opening area. I have tried it with cached interpreter, parallel-rdp and parallel-rsp and it still crashes. When using the same plugins on the Parallel core it does not crash. If there is a way to do logging, I'll gladly do so!

Here is a save state: https://www.dropbox.com/s/24nqn08az432wot/Legend%20of%20Zelda%2C%20The%20-%20The%20Missing%20Link%20%5BHack%20by%20Kaze%2C%20Zel%20%26%20CDi-Fails%20v2.0%5D.state?dl=0

**Comment by Tasosgemah** [comment] 2022-01-10 19:40
Try pure interpreter.

**Comment by krispya** [comment] 2022-01-10 21:01
Same crash with pure interpreter.

**Comment by m4xw** [comment] 2022-01-11 12:31
Use dynarec, run retroarch with --verbose and upload the log. Might shed some light on this

**Comment by Tasosgemah** [comment] 2022-01-11 14:33
Strange, i use the same core and plugin and i don't get crashes with interpreter. I did get a crash in an unrelated situation with dynarec.

**Comment by krispya** [comment] 2022-01-11 18:27
Here is the log generated using the save state from above: https://www.dropbox.com/s/mqsjz9nvri85s2u/retroarch.log?dl=0

Here is my config for Mupen: https://www.dropbox.com/s/7or7qb92djl6riy/Mupen64Plus-Next.opt?dl=0

@Tasosgemah could you share your config with me? I can see if it runs without a crash on my end.

**Comment by m4xw** [comment] 2022-01-11 19:22
That smells like the potential frontend issue i noticed with debug oot and isviewer.
The idea is that the logging itself causes the crash.

**Comment by krispya** [comment] 2022-01-11 19:28
I'm using Windows 10 x64 v1.9.14. Another user who first reported the issue to me is also using the same platform and version.

**Comment by m4xw** [comment] 2022-01-11 19:28
do you have log to file on? if yes, try it off (prolly same  result tho).
Make sure you try the non-qt ver as well

**Comment by m4xw** [comment] 2022-01-11 19:29
at least thats the only thing u can do other than maybe disable logging completely (without changing code)

**Comment by m4xw** [comment] 2022-01-11 19:29
If we can at least confirm the cause tho, I can go for a fix

**Comment by krispya** [comment] 2022-01-11 19:33
It's the same issue with logging off. I only turned on logging for this last crash.

**Comment by m4xw** [comment] 2022-01-11 19:45
try https://m4xw.net/nextcloud/index.php/s/J8Xeez7z5PBLzGw

**Comment by krispya** [comment] 2022-01-11 20:07
Eureka! That works.

**Comment by m4xw** [comment] 2022-01-11 20:38
technically not a mupen bug i guess... leaving it open till frontend fix for information purposes

**Comment by Jj0YzL5nvJ** [comment] 2022-01-12 02:52
mupen64plus/mupen64plus-core#909

**Comment by m4xw** [comment] 2022-01-12 10:31
Thats what i get for not using a debugger.
Thanks

**Comment by m4xw** [comment] 2022-01-12 14:18
fixed on develop

**Closed by m4xw** 2022-01-12 14:18 UTC
Labels: information, mitigate
