### ISSUE TITLE
[Feature Request] Widescreen option when using parallel LLE

### ISSUE THREAD

**Issue by mark007** [libretro/mupen64plus-libretro-nx#410] opened 2021-12-28 01:02 UTC
I have been using the parallel-64 core for some time now but today have switched to the mupen64plus-next and have also set it to use parallel lle.

One feature I realized was missing was widescreen mode. I mainly use this in GoldenEye 64 when I set its in game (in the watch) output to be appropriate for a widescreen display, and could then set the parallel-64 core to also scale the image to widescreen to keep things in proportion. This worked great.

This is a feature request to see can the same be done for mupel64plus, where I guess it could have an option, thats parallel specific, that lets you choose to scale to 16:9 ratio if selected, and the user could set it per game that uses it (eg GoldenEye 64).

**Comment by m4xw** [comment] 2022-01-04 13:05
Dupe of https://github.com/libretro/mupen64plus-libretro-nx/issues/312
I might bump prio tho since its a trivial change. Ofc it will need game patches and/or game support to work for LLE

**Closed by m4xw** 2022-01-04 13:05 UTC

**Comment by mark007** [comment] 2022-01-04 13:12
Thank you
