### ISSUE TITLE
[Linux] Core cannot be loaded on Ubuntu Disco Dingo

### ISSUE THREAD

**Issue by MojoJojoDojo** [libretro/mupen64plus-libretro-nx#90] opened 2019-08-27 16:03 UTC
As the title says.
Tried loading it using the "Load Core" and it cant load it.
All the other cores i have load correctly.

**Comment by m4xw** [comment] 2019-08-27 16:06
You are probably missing dependencies.
Dupe of #78

**Closed by m4xw** 2019-08-27 16:06 UTC
