### ISSUE TITLE
Can run N64 rom on raspberry pi 3 b+ 

### ISSUE THREAD

**Issue by frani** [libretro/mupen64plus-libretro-nx#361] opened 2021-07-20 04:56 UTC
trying run worms-armageddon in core Nintendo 64 (ParaLLEI N64)
```
Lakka:~ # systemctl stop retroarch.service ; retroarch -v
wifi is already enabled
ALSA lib /home/lakkabuildbot/release/Lakka-LibreELEC/build.Lakka-RPi2.arm/alsa-lib-1.2.3.2/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
plugin_start_gfx
wifi is already enabled
ALSA lib /home/lakkabuildbot/release/Lakka-LibreELEC/build.Lakka-RPi2.arm/alsa-lib-1.2.3.2/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
unknown NIR ALU inst: vec1 32 ssa_124 = umin ssa_55, ssa_57
Aborted
```

trying run worms-armageddon in core Nintendo 64 (Mupen64Plus-Next)
Lakka:~ # systemctl stop retroarch.service ; retroarch -v
wifi is already enabled
ALSA lib /home/lakkabuildbot/release/Lakka-LibreELEC/build.Lakka-RPi2.arm/alsa-lib-1.2.3.2/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
context_reset.
ReadSpecialSettings: DEFAULT
plugin_start_gfx success.
Gfx RomOpen.
ReadSpecialSettings: DEFAULT
ReadSpecialSettings: WORMS ARMAGEDDON
GL_ARB_texture_non_power_of_two supported.
GL_EXT_texture_format_BGRA8888 supported.
GL_ARB_texture_non_power_of_two supported.
GL_EXT_texture_format_BGRA8888 supported.
wifi is already enabled
ALSA lib /home/lakkabuildbot/release/Lakka-LibreELEC/build.Lakka-RPi2.arm/alsa-lib-1.2.3.2/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
Segmentation fault

**Comment by m4xw** [comment] 2021-07-23 11:35
dupe of #357

**Closed by m4xw** 2021-07-23 11:35 UTC
