### ISSUE TITLE
ParaLLel RDP/RSP fails to load on windows 11 / AMD GPU

### ISSUE THREAD

**Issue by gravitone** [libretro/mupen64plus-libretro-nx#399] opened 2021-11-08 11:32 UTC
Core loads for a brief moment but fails and crashes retroarch right after when loading any rom.
Consistent behavior on fresh install, clean config
[retroarch__2021_11_08__12_26_27.log](https://github.com/libretro/mupen64plus-libretro-nx/files/7496578/retroarch__2021_11_08__12_26_27.log)
.

**Comment by m4xw** [comment] 2021-11-08 11:36
Got a crash log/trace?

**Comment by gravitone** [comment] 2021-11-08 11:44
Afraid not, don't have a dev environment setup on this system. I had both retroarch and core logging set to level 0 debugging, but it doesn't seem like any exceptions are thrown?

**Comment by Immersion95** [comment] 2021-12-26 08:40
Parallel RDP never worked with AMD 6x00 cards since launch unfortunately whether it's Vulkan/GL.

Is there anything that we can do to pinpoint the problem ?

**Comment by markovikich** [comment] 2022-02-04 00:20
Works perfectly fine with mesa on Linux, so it seems like a Windows driver issue. The PJ64 port works perfectly fine as well however it apparently outputs with an OpenGL context instead of Vulkan, so maybe the issue lies there? ([more info on this blog](https://mudlord.github.io/Parallel-RDP/))

Also, when launching a game with the log terminal open it says: `[WARN]: Current proprietary AMD driver is known to be buggy with 8/16-bit integer arithmetic, disabling support for time being.` Maybe this is related?

**Comment by Immersion95** [comment] 2022-02-27 18:58
Unfortunately Parallel RDP still doesn't work AMD RDNA2. Those cards were released in late 2020 so I think it's useless to wait for a solution.

The only alternative is m64p and it's working really great.

I'm slowly moving out of RetroArch unfortunately as cores and getting less and less updated (this one, MAME, PCSX2, Beetle, Dolphin).

**Comment by Schroedingers-Cat** [comment] 2022-05-22 18:11
> Got a crash log/trace?  

This is what I got from running `retroarch.exe -v` when the crash happened:
[retroarch-paraLLEl-Win-crash.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/8749954/retroarch-paraLLEl-Win-crash.txt)  
Anything else you need for analysis?  

The crash also happens on Windows 10 and it looks like only users with a recent AMD GPU are affected on the Windows platform. It happens with the paraLLEl RDP plugin (RSP works fine on retroarch 1.10.3) in mupen64plus-next core or when using the paraLLEl core. Vulkan is used in both cases as video driver. This only started to happen when I got the RX 6900XT into my system and it worked fine with the GTX 1070 that I used before.  None of these crashes occur on the same hardware on Manjaro/Gnome 42. It's also working fine on the Steam Deck (current SteamOS beta).

**Comment by Immersion95** [comment] 2022-05-23 22:34
It has been in this state since the RDNA2 launch in 2020. I think it's better to move to m64p if you want to use Parallel RDP as there is no other way.

**Comment by m4xw** [comment] 2022-05-24 09:17
> > Got a crash log/trace?
> 
> This is what I got from running `retroarch.exe -v` when the crash happened: [retroarch-paraLLEl-Win-crash.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/8749954/retroarch-paraLLEl-Win-crash.txt) Anything else you need for analysis?
> 
> The crash also happens on Windows 10 and it looks like only users with a recent AMD GPU are affected on the Windows platform. It happens with the paraLLEl RDP plugin (RSP works fine on retroarch 1.10.3) in mupen64plus-next core or when using the paraLLEl core. Vulkan is used in both cases as video driver. This only started to happen when I got the RX 6900XT into my system and it worked fine with the GTX 1070 that I used before. None of these crashes occur on the same hardware on Manjaro/Gnome 42. It's also working fine on the Steam Deck (current SteamOS beta).

No issue on a rx 5700 with xt bios btw.
For AMD make sure their sw isnt trying to upscale stuff because it can blow things out of proportion.



> It has been in this state since the RDNA2 launch in 2020. I think it's better to move to m64p if you want to use Parallel RDP as there is no other way.

the only diff is frame presentation being via GL, which is not a core issue by design as its handled by the frontend.

**Comment by Schroedingers-Cat** [comment] 2022-05-24 12:25
> No issue on a rx 5700 with xt bios btw.  

That’s an RDNA(1) so it seems to fine with these GPUs, then.  

> For AMD make sure their sw isnt trying to upscale stuff because it can blow things out of proportion.

I only have the AMD Radeon driver (22.5.1) installed without any of the adrenaline services. So the upscaling stuff shouldn’t interfere.  

Is there anything else I can do to get you more info about this crash?

**Comment by m4xw** [comment] 2022-05-24 12:43
Sorry, small mistake.
Try https://git.libretro.com/libretro/RetroArch/-/jobs/1994701

**Comment by m4xw** [comment] 2022-05-24 15:25
I verified its a driver bug, crash in vkCreateComputePipelines, might be related t some internal float optimizations :/
Probably a won't fix, can work around at best.
I did uncover a few other issues tho, but they didnt seem to contribute.

**Comment by Schroedingers-Cat** [comment] 2022-05-24 20:38
@m4xw sorry, I wasn't fast enough.  

If it's a driver bug, it would be best to report it. This seems to be the best place unless you know a better one? https://www.amd.com/en/support/kb/faq/amdbrt  

Btw., how did you reproduce this bug if you're on an RDNA(1) GPU?

**Comment by Intothisworld** [comment] 2022-05-25 03:01
Tried to get my friend set up to play OoT with ParaLLel today and he experienced this same issue. Instant crash upon loading up the game. He's using 64-bit Windows 10 and a Radeon RX 6700 XT. Let me know if there's anything I can do to help.

**Comment by m4xw** [comment] 2022-05-25 09:43
> @m4xw sorry, I wasn't fast enough. The build artifacts are already gone.
> 
> If it's a driver bug, it would be best to report it. This seems to be the best place unless you know a better one? https://www.amd.com/en/support/kb/faq/amdbrt
> 
> Btw., how did you reproduce this bug if you're on an RDNA(1) GPU?

Someone with a 6900xt offered to test.
The very same crash was actually reported to AMD for RDNA1 but supposedly is already fixed in driver since 2021, so something is smelly imo

**Comment by m4xw** [comment] 2022-05-25 13:50
Workaround in https://github.com/libretro/mupen64plus-libretro-nx/commit/9beacb26c543cc88c57ed96ca0a72c1925827870
Proper fix will follow.

**Closed by m4xw** 2022-05-25 13:50 UTC

**Comment by EmuAl** [comment] 2022-05-25 22:07
is this something i can test ?
i tried updating libretro core but i've still got same problem
works from vulkan to glcore but doesn't from glcore to glcore

**Comment by Immersion95** [comment] 2022-08-15 06:45
It's crashing again with latest 22.8.1 drivers, previous ones were working perfectly with this fix.

**Comment by Schroedingers-Cat** [comment] 2022-08-15 15:52
Hm, working fine here with Retroarch 1.10.3, Mupen64Plus-Next 2.4-Vulkan 9beacb2 / 4684cfa and the ParaLLEl plugins on the AMD driver v22.8.1.

**Comment by Immersion95** [comment] 2022-08-15 17:17
> Hm, working fine here with Retroarch 1.10.3, Mupen64Plus-Next 2.4-Vulkan [9beacb2](https://github.com/libretro/mupen64plus-libretro-nx/commit/9beacb26c543cc88c57ed96ca0a72c1925827870) / [4684cfa](https://github.com/libretro/mupen64plus-libretro-nx/commit/4684cfa56ae7752be284eaaa165c1dc34ec63eb7) and the ParaLLEl plugins on the AMD driver v22.8.1.

Thanks for testing, I clean installed everything and it's working now :)

**Comment by Immersion95** [comment] 2022-08-17 17:49
> Hm, working fine here with Retroarch 1.10.3, Mupen64Plus-Next 2.4-Vulkan [9beacb2](https://github.com/libretro/mupen64plus-libretro-nx/commit/9beacb26c543cc88c57ed96ca0a72c1925827870) / [4684cfa](https://github.com/libretro/mupen64plus-libretro-nx/commit/4684cfa56ae7752be284eaaa165c1dc34ec63eb7) and the ParaLLEl plugins on the AMD driver v22.8.1.

Found the culprit, Steam Big Picture + AMD Driver 22.8.1 + Mupen core + Parallel RDP -->Crash
I had to revert to 22.7.1
