### ISSUE TITLE
Oot randomizer crashing

### ISSUE THREAD

**Issue by LordCrackerJakc** [libretro/mupen64plus-libretro-nx#88] opened 2019-08-25 05:24 UTC
I’ve been playing an oot randomizer on my laptop, but the game will occasionally crash. The image will completely freeze, but the sound will continue. If I load a save state from the frozen position it just shows a blank screen (even after restarting the rom). Anyone else encountered this and or have any tips?

**Comment by m4xw** [comment] 2019-08-26 09:34
Dupe of #49

**Closed by m4xw** 2019-08-26 09:34 UTC
