### ISSUE TITLE
[Windows x64] Legend of Zelda: Ocarina of Time random crashes

### ISSUE THREAD

**Issue by PavelDurov1488** [libretro/mupen64plus-libretro-nx#283] opened 2020-11-28 14:33 UTC
Hello and thanks for your project :)

Now I play LOZ: Ocarina of Time and have some random crashes

There is Mupen config

mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "320x240"
mupen64plus-alt-map = "True"
mupen64plus-angrylion-multithread = "all threads"
mupen64plus-angrylion-overscan = "disabled"
mupen64plus-angrylion-sync = "Low"
mupen64plus-angrylion-vioverlay = "Filtered"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "20"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-DitheringPattern = "True"
mupen64plus-DitheringQuantization = "False"
mupen64plus-EnableCopyAuxToRDRAM = "False"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHiResAltCRC = "False"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResFactor = "0"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-HybridFilter = "True"
mupen64plus-IgnoreTLBExceptions = "False"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "rumble"
mupen64plus-pak2 = "memory"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-parallel-rdp-deinterlace-method = "Bob"
mupen64plus-parallel-rdp-dither-filter = "True"
mupen64plus-parallel-rdp-divot-filter = "True"
mupen64plus-parallel-rdp-downscaling = "disable"
mupen64plus-parallel-rdp-gamma-dither = "True"
mupen64plus-parallel-rdp-native-tex-rect = "True"
mupen64plus-parallel-rdp-native-texture-lod = "False"
mupen64plus-parallel-rdp-overscan = "0"
mupen64plus-parallel-rdp-super-sampled-read-back = "False"
mupen64plus-parallel-rdp-super-sampled-read-back-dither = "True"
mupen64plus-parallel-rdp-synchronous = "True"
mupen64plus-parallel-rdp-upscaling = "1x"
mupen64plus-parallel-rdp-vi-aa = "True"
mupen64plus-parallel-rdp-vi-bilinear = "True"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-RDRAMImageDitheringMode = "False"
mupen64plus-rsp-plugin = "parallel"
mupen64plus-ThreadedRenderer = "False"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"

If its important, I will attach retroarch.cfg file (github can not attach cfg file, so I added txt extension)
[retroarch.cfg.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/5610731/retroarch.cfg.txt)

**Comment by m4xw** [comment] 2020-11-30 12:33
Dupe of #180

**Closed by m4xw** 2020-11-30 12:33 UTC
